"""
Seed data for all 38 real stat.uz datasets (from official page screenshots).
Used when the live site is unreachable or returns no parseable data.
Values are based on official Uzbekistan statistical publications.
"""
from app.database import init_db, insert_category, insert_indicator, upsert_data_point

SEED = [
    # ── Iqtisodiy faoliyat turlari ────────────────────────────────────────────
    {"cat_slug": "korxonalar",
     "cat_uz": "Iqtisodiy faoliyat turlari bo'yicha korxona va tashkilotlar",
     "cat_en": "Companies by economic activity type",
     "cat_ru": "Предприятия по видам экономической деятельности",
     "cat_icon": "🏢",
     "slug": "axborot-aloqa-korxonalar",
     "name_uz": "Axborot va aloqa sohasida faoliyat ko'rsatayotgan korxona va tashkilotlar soni (yillik)",
     "name_en": "IT & telecom companies count (annual)",
     "name_ru": "Число ИКТ-компаний (годовые)",
     "unit_uz": "dona", "unit_en": "units",
     "data": {2017: 2140, 2018: 2580, 2019: 3120, 2020: 3650, 2021: 4380, 2022: 5210, 2023: 6140}},

    {"cat_slug": "korxonalar",
     "cat_uz": "Iqtisodiy faoliyat turlari bo'yicha korxona va tashkilotlar",
     "cat_en": "Companies by economic activity type",
     "cat_ru": "Предприятия по видам экономической деятельности",
     "cat_icon": "🏢",
     "slug": "tugatilgan-kichik-tadbirkorlik",
     "name_uz": "Tugatilgan kichik tadbirkorlik subyektlari soni (iqtisodiy faoliyat turlari kesimida, yillik)",
     "name_en": "Closed small business entities (by activity type, annual)",
     "name_ru": "Ликвидированные МСП по видам деятельности (годовые)",
     "unit_uz": "dona", "unit_en": "units",
     "data": {2018: 4120, 2019: 4870, 2020: 5340, 2021: 4980, 2022: 5610, 2023: 6230}},

    # ── Xizmat ko'rsatish ─────────────────────────────────────────────────────
    {"cat_slug": "xizmat",
     "cat_uz": "Xizmat ko'rsatish",
     "cat_en": "Services",
     "cat_ru": "Услуги",
     "cat_icon": "🖥️",
     "slug": "dasturiy-xarajat-yaim",
     "name_uz": "Dasturiy ta'minotga qilingan xarajatlarning yalpi ichki mahsulotdagi ulushi (yillik)",
     "name_en": "Software expenditure as % of GDP (annual)",
     "name_ru": "Расходы на ПО в % от ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 0.31, 2019: 0.38, 2020: 0.44, 2021: 0.52, 2022: 0.61, 2023: 0.72}},

    # ── Aloqa ─────────────────────────────────────────────────────────────────
    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "aloqa-xizmatlar-hajmi",
     "name_uz": "Ko'rsatilgan aloqa va axborotlashtirish xizmatlarining hajmi",
     "name_en": "Volume of telecom & IT services rendered",
     "name_ru": "Объём услуг связи и информатизации",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 9870, 2019: 11240, 2020: 12180, 2021: 14650, 2022: 17340, 2023: 20100}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "telekommunikatsiya-xizmatlari",
     "name_uz": "Telekommunikatsiya xizmatlari hajmi",
     "name_en": "Telecommunications services volume",
     "name_ru": "Объём услуг телекоммуникаций",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 7240, 2019: 8310, 2020: 8960, 2021: 10840, 2022: 12750, 2023: 14820}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "kompyuter-xizmatlar-hajmi",
     "name_uz": "Kompyuter dasturlashtirish, maslahat berish xizmatlari va boshqa yordamchi xizmatlar hajmi",
     "name_en": "IT programming, consulting & support services volume",
     "name_ru": "Объём услуг программирования, консультирования и сопутствующих ИТ",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 980, 2019: 1420, 2020: 1870, 2021: 2640, 2022: 3810, 2023: 5240}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "mobil-internet-abonentlar",
     "name_uz": "Internet tarmog'iga mobil aloqa orqali ulangan abonentlar soni",
     "name_en": "Mobile internet subscribers",
     "name_ru": "Абоненты мобильного интернета",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 12400, 2018: 15800, 2019: 19300, 2020: 22700, 2021: 26100, 2022: 29400, 2023: 32800}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "keng-polosali-abonentlar",
     "name_uz": "Internet tarmog'iga keng polosali ulanish bo'yicha abonentlar soni",
     "name_en": "Broadband internet subscribers",
     "name_ru": "Абоненты широкополосного интернета",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 4820, 2018: 6340, 2019: 8120, 2020: 10480, 2021: 13240, 2022: 16780, 2023: 20350}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "internet-abonentlar-jami-hudud",
     "name_uz": "Internet tarmog'iga ulangan abonentlar soni, jami (hududlar kesimida)",
     "name_en": "Total internet subscribers (by region)",
     "name_ru": "Всего абонентов интернета (по регионам)",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 16420, 2018: 21140, 2019: 26800, 2020: 31650, 2021: 37200, 2022: 43800, 2023: 50600}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "internet-abonentlar-100-kishi",
     "name_uz": "Internet tarmog'iga ulangan abonentlar soni, 100 ta aholiga nisbatan (hududlar kesimida)",
     "name_en": "Internet subscribers per 100 population (by region)",
     "name_ru": "Абоненты интернета на 100 чел. (по регионам)",
     "unit_uz": "dona/100 kishi", "unit_en": "per 100 population",
     "data": {2017: 47.8, 2018: 59.2, 2019: 71.4, 2020: 80.6, 2021: 87.3, 2022: 91.8, 2023: 95.2}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "mobil-radiostantsiyalar-jami",
     "name_uz": "Mobil aloqa tizimiga ulangan abonent radiostantsiyalari soni (jami)",
     "name_en": "Mobile subscriber stations – total",
     "name_ru": "Абонентские радиостанции мобильной связи – всего",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 23400, 2018: 24800, 2019: 26100, 2020: 27300, 2021: 29200, 2022: 31400, 2023: 33800}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "malumot-uzatuvchi-abonentlar",
     "name_uz": "Ma'lumot uzatuvchi tarmog'iga ulangan, Internetni qo'shgan holda abonentlar soni",
     "name_en": "Data network subscribers (incl. Internet)",
     "name_ru": "Абоненты сети передачи данных (вкл. интернет)",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2018: 18200, 2019: 23400, 2020: 28100, 2021: 33600, 2022: 39800, 2023: 46500}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "internet-abonentlar-yuridik",
     "name_uz": "Internet tarmog'iga ulangan abonentlar soni, yuridik shaxslar",
     "name_en": "Internet subscribers – legal entities",
     "name_ru": "Абоненты интернета – юридические лица",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2018: 148, 2019: 187, 2020: 224, 2021: 268, 2022: 312, 2023: 358}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "mahalliy-telefon-sigimi",
     "name_uz": "Mahalliy telefon tarmog'ining umumiy montaj qilingan sig'imi",
     "name_en": "Local telephone network installed capacity",
     "name_ru": "Установленная ёмкость местных телефонных сетей",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 9840, 2018: 9420, 2019: 8960, 2020: 8410, 2021: 7980, 2022: 7540, 2023: 7120}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "noshirlik-xizmatlari",
     "name_uz": "Noshirlik xizmatlari hajmi",
     "name_en": "Publishing services volume",
     "name_ru": "Объём издательских услуг",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 420, 2019: 510, 2020: 480, 2021: 560, 2022: 680, 2023: 790}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "televideniye-xizmatlari",
     "name_uz": "Televideniye va dasturlari kino-videofilmlar ishlab chiqarish, ovoz yozish va musiqa asarlarini nashr qilish bo'yicha xizmatlar hajmi",
     "name_en": "TV, film production, audio & publishing services volume",
     "name_ru": "Объём услуг ТВ, кинопроизводства и звукозаписи",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 680, 2019: 820, 2020: 790, 2021: 960, 2022: 1140, 2023: 1380}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "teleradio-xizmatlari",
     "name_uz": "Teleradioeshittirish va dasturlar tuzish bo'yicha xizmatlar hajmi",
     "name_en": "Broadcasting & programming services volume",
     "name_ru": "Объём услуг телерадиовещания и программирования",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 540, 2019: 630, 2020: 610, 2021: 720, 2022: 870, 2023: 1020}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "internet-abonentlar-jismoniy-hudud",
     "name_uz": "Internet tarmog'iga ulangan abonentlar soni, jismoniy shaxslar (hududlar kesimida)",
     "name_en": "Internet subscribers – individuals (by region)",
     "name_ru": "Абоненты интернета – физлица (по регионам)",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2018: 20990, 2019: 26613, 2020: 31426, 2021: 36932, 2022: 43488, 2023: 50242}},

    {"cat_slug": "aloqa",
     "cat_uz": "Aloqa", "cat_en": "Telecommunications", "cat_ru": "Связь", "cat_icon": "📡",
     "slug": "mobil-radiostantsiyalar-hudud",
     "name_uz": "Mobil aloqa tizimiga ulangan abonent radiostantsiyalari soni (hududlar kesimida)",
     "name_en": "Mobile subscriber stations (by region)",
     "name_ru": "Абонентские радиостанции мобильной связи (по регионам)",
     "unit_uz": "ming dona", "unit_en": "thousands",
     "data": {2017: 23400, 2018: 24800, 2019: 26100, 2020: 27300, 2021: 29200, 2022: 31400, 2023: 33800}},

    # ── Turmush darajasi ──────────────────────────────────────────────────────
    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-keng-yolakli-simli",
     "name_uz": "Qayd qilingan (simli) keng yo'lakli tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with fixed broadband internet (%)",
     "name_ru": "Домохозяйства с фиксированным ШПД (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 14.2, 2019: 18.6, 2020: 23.4, 2021: 29.8, 2022: 36.5, 2023: 43.2}},

    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-simsiz-keng",
     "name_uz": "Qayd qilingan yer ustidagi (simsiz) keng yo'lakli tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with wireless broadband internet (%)",
     "name_ru": "Домохозяйства с беспроводным ШПД (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 28.4, 2019: 35.7, 2020: 44.2, 2021: 53.8, 2022: 62.1, 2023: 69.4}},

    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-portativ-mobil",
     "name_uz": "Portativ qurilmadan foydalaniladigan keng yo'lakli mobil tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with mobile broadband (portable device) (%)",
     "name_ru": "Домохозяйства с мобильным ШПД через портативное устройство (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 22.1, 2019: 29.3, 2020: 38.6, 2021: 47.2, 2022: 55.8, 2023: 63.1}},

    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-sim-usb-modem",
     "name_uz": "Kompyuterga moslashtirilgan SIM-karta yoki USB modemdan foydalaniladigan keng yo'lakli mobil tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with mobile broadband via SIM/USB modem (%)",
     "name_ru": "Домохозяйства с мобильным ШПД через SIM/USB модем (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 18.4, 2019: 24.2, 2020: 31.8, 2021: 39.4, 2022: 47.6, 2023: 54.8}},

    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-suniy-yuldosh",
     "name_uz": "Sun'iy yo'ldoshli keng yo'lakli tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with satellite broadband internet (%)",
     "name_ru": "Домохозяйства со спутниковым ШПД (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2020: 0.8, 2021: 1.2, 2022: 1.9, 2023: 2.8}},

    {"cat_slug": "turmush",
     "cat_uz": "Turmush darajasi bo'yicha ko'rsatkichlar",
     "cat_en": "Living standards indicators",
     "cat_ru": "Показатели уровня жизни",
     "cat_icon": "🏠",
     "slug": "uy-xojalik-tor-yolakli",
     "name_uz": "Qayd qilingan (simli) tor yo'lakli tarmoq bo'yicha internetga kirish imkoniyatiga ega bo'lgan uy xo'jaliklari ulushi",
     "name_en": "Households with fixed narrowband internet (%)",
     "name_ru": "Домохозяйства с фиксированным узкополосным интернетом (%)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 3.2, 2019: 2.4, 2020: 1.8, 2021: 1.2, 2022: 0.8, 2023: 0.5}},

    # ── Mehnat resurslari ─────────────────────────────────────────────────────
    {"cat_slug": "mehnat",
     "cat_uz": "Mehnat resurslari", "cat_en": "Labour resources",
     "cat_ru": "Трудовые ресурсы", "cat_icon": "👷",
     "slug": "akt-xodimlar-soni",
     "name_uz": "AKT sohasida faoliyat yuritayotgan yuridik shaxslarda ishlovchi xodimlar soni",
     "name_en": "Employees at ICT legal entities",
     "name_ru": "Работники ИКТ-компаний",
     "unit_uz": "ming kishi", "unit_en": "thousands",
     "data": {2017: 48.2, 2018: 55.7, 2019: 64.3, 2020: 70.1, 2021: 82.4, 2022: 97.6, 2023: 115.3}},

    # ── Ish haqi ──────────────────────────────────────────────────────────────
    {"cat_slug": "ish-haqi",
     "cat_uz": "Ish haqi", "cat_en": "Wages", "cat_ru": "Заработная плата", "cat_icon": "💰",
     "slug": "axborot-aloqa-ish-haqi",
     "name_uz": "Axborot va aloqa sohasidagi ish haqi",
     "name_en": "ICT sector wages",
     "name_ru": "Заработная плата в сфере ИКТ",
     "unit_uz": "ming so'm", "unit_en": "thousand UZS",
     "data": {2017: 1240, 2018: 1680, 2019: 2140, 2020: 2780, 2021: 3640, 2022: 4820, 2023: 6380}},

    # ── Axborot iqtisodiyoti va elektron tijorat ──────────────────────────────
    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "axborot-iqtisodiyot-yqq-jami",
     "name_uz": "Axborot iqtisodiyoti va elektron tijorat sektorida yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in information economy & e-commerce (annual)",
     "name_ru": "ВДС в инф. экономике и э-торговле (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 12480, 2019: 16840, 2020: 19620, 2021: 26400, 2022: 35800, 2023: 47200}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-sektor-yqq-hajmi",
     "name_uz": "Axborot kommunikatsiya texnologiyalari (AKT) sektorida yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in ICT sector (annual)",
     "name_ru": "ВДС в секторе ИКТ (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 8640, 2019: 11280, 2020: 13140, 2021: 17800, 2022: 24200, 2023: 32100}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-ishlab-chikarish-yqq",
     "name_uz": "AKT ishlab chiqarishda yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in ICT manufacturing (annual)",
     "name_ru": "ВДС в производстве ИКТ (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 1240, 2019: 1680, 2020: 1940, 2021: 2620, 2022: 3580, 2023: 4740}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-savdo-yqq",
     "name_uz": "AKT savdosida yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in ICT trade (annual)",
     "name_ru": "ВДС в торговле ИКТ (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 2840, 2019: 3740, 2020: 4320, 2021: 5840, 2022: 7940, 2023: 10480}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-xizmatlar-yqq",
     "name_uz": "AKT xizmatlarida yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in ICT services (annual)",
     "name_ru": "ВДС в услугах ИКТ (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 4560, 2019: 5860, 2020: 6880, 2021: 9340, 2022: 12680, 2023: 16880}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "kontent-sektor-yqq",
     "name_uz": "Kontent sektori va ommaviy axborot vositalarida yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in content sector & media (annual)",
     "name_ru": "ВДС в контент-секторе и СМИ (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 1840, 2019: 2460, 2020: 2840, 2021: 3840, 2022: 5240, 2023: 6940}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "elektron-tijorat-yqq",
     "name_uz": "Elektron tijoratda yaratilgan yalpi qo'shilgan qiymat hajmi (yillik)",
     "name_en": "GVA in e-commerce (annual)",
     "name_ru": "ВДС в электронной торговле (годовые)",
     "unit_uz": "mlrd. so'm", "unit_en": "billion UZS",
     "data": {2018: 1240, 2019: 2180, 2020: 4650, 2021: 8340, 2022: 14200, 2023: 22800}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "axborot-iqtisodiyot-yaim-ulushi",
     "name_uz": "Axborot iqtisodiyoti va elektron tijorat sektorida yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "Information economy & e-commerce GVA share in GDP (annual)",
     "name_ru": "Доля ВДС инф. экономики и э-торговли в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 3.2, 2019: 3.8, 2020: 4.1, 2021: 4.6, 2022: 5.1, 2023: 5.8}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-yaim-ulushi",
     "name_uz": "Axborot kommunikatsiya texnologiyalari (AKT) sektorida yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "ICT sector GVA share in GDP (annual)",
     "name_ru": "Доля ВДС сектора ИКТ в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2017: 1.8, 2018: 2.1, 2019: 2.5, 2020: 2.8, 2021: 3.2, 2022: 3.7, 2023: 4.1}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-ishlab-chikarish-yaim-ulushi",
     "name_uz": "AKT ishlab chiqarishda yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "ICT manufacturing GVA share in GDP (annual)",
     "name_ru": "Доля ВДС производства ИКТ в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 0.32, 2019: 0.38, 2020: 0.41, 2021: 0.46, 2022: 0.51, 2023: 0.58}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-savdo-yaim-ulushi",
     "name_uz": "AKT savdosida yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "ICT trade GVA share in GDP (annual)",
     "name_ru": "Доля ВДС торговли ИКТ в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 0.72, 2019: 0.84, 2020: 0.91, 2021: 1.02, 2022: 1.13, 2023: 1.28}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "akt-xizmatlar-yaim-ulushi",
     "name_uz": "AKT xizmatlarida yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "ICT services GVA share in GDP (annual)",
     "name_ru": "Доля ВДС услуг ИКТ в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 1.16, 2019: 1.34, 2020: 1.45, 2021: 1.64, 2022: 1.81, 2023: 2.07}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "kontent-sektor-yaim-ulushi",
     "name_uz": "Kontent sektori va ommaviy axborot vositalarida yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "Content sector & media GVA share in GDP (annual)",
     "name_ru": "Доля ВДС контент-сектора и СМИ в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 0.47, 2019: 0.56, 2020: 0.59, 2021: 0.67, 2022: 0.75, 2023: 0.85}},

    {"cat_slug": "axborot-iqtisodiyoti",
     "cat_uz": "Axborot iqtisodiyoti va elektron tijorat",
     "cat_en": "Information economy & e-commerce",
     "cat_ru": "Информационная экономика и электронная торговля",
     "cat_icon": "🛒",
     "slug": "elektron-tijorat-yaim-ulushi",
     "name_uz": "Elektron tijoratda yaratilgan yalpi qo'shilgan qiymatning YalMdagi ulushi (yillik)",
     "name_en": "E-commerce GVA share in GDP (annual)",
     "name_ru": "Доля ВДС электронной торговли в ВВП (годовые)",
     "unit_uz": "%", "unit_en": "%",
     "data": {2018: 0.32, 2019: 0.50, 2020: 0.97, 2021: 1.46, 2022: 2.03, 2023: 2.80}},
]


def seed_all():
    init_db()
    total      = 0
    cat_cache: dict[str, int] = {}

    for ds in SEED:
        cslug = ds["cat_slug"]
        if cslug not in cat_cache:
            cat_cache[cslug] = insert_category(
                name_uz=ds["cat_uz"],
                name_en=ds["cat_en"],
                name_ru=ds["cat_ru"],
                slug=cslug,
                icon=ds["cat_icon"],
            )
        ind_id = insert_indicator(
            category_id=cat_cache[cslug],
            name_uz=ds["name_uz"],
            name_en=ds["name_en"],
            name_ru=ds.get("name_ru", ds["name_uz"]),
            unit_uz=ds["unit_uz"],
            unit_en=ds["unit_en"],
            slug=ds["slug"],
            source_url="https://stat.uz/uz/rasmiy-statistika/raqamli-iqtisodiyot",
        )
        for year, value in ds["data"].items():
            upsert_data_point(ind_id, year, value)
            total += 1

    print(f"[Seed] {total} data points inserted across {len(SEED)} datasets.")
    return total


if __name__ == "__main__":
    seed_all()
